//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelStart5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactId { get; set; }
        public string Title { get; set; }
        public string Fname { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public Nullable<int> DialCode { get; set; }
        public string MobileNo { get; set; }
        public string Id { get; set; }
    }
}
