//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelStart5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int hotelID { get; set; }
        public string Location { get; set; }
        public string hotel1 { get; set; }
        public string Address { get; set; }
        public string Rating { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
