//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelStart5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traveller
    {
        public int TravellerID { get; set; }
        public string Title { get; set; }
        public string Fname { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string DOB { get; set; }
        public string sitNo { get; set; }
        public string Id { get; set; }
    }
}
